---
kind: Service
apiVersion: v1
metadata:
  name: juice-shop
  namespace: default
spec:
  selector:
    app.kubernetes.io/instance: juice-shop
  ports:
    - name: http
      port: 8000
      targetPort: 3000
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: juice-shop
  namespace: default
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: juice-shop
    spec:
      containers:
        - name: juice-shop
          image: bkimminich/juice-shop
  selector:
    matchLabels:
      app.kubernetes.io/instance: juice-shop
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  namespace: default
  name: juiceshop
spec:
  parentRefs:
    - kind: Gateway
      name: gw
      namespace: default
  hostnames:
    - juiceshop.172-19-0-2.nip.io
  rules:
    - backendRefs:
        - kind: Service
          name: juice-shop
          port: 8000
      matches:
        - path:
            type: PathPrefix
            value: /
