---
apiVersion: oss.u-s-p.ch/v1alpha1
kind: CorazaWaf
metadata:
  name: juiceshop
  namespace: default
spec:
  backend:
    hostname: "juice-shop"
    port: 8000
  crs:
    paranoiaLevel:
      detecting: 2
      enforcing: 1
